### ISSUE TITLE
Add CRN to Course Page

### ISSUE THREAD

**Issue by AlexTheZoomer** [theobourgeois/DalSearch#1]
Just a suggestion, if it could be at all possible to add the CRN to a course's page, that would be amazing.

**Comment by theobourgeois** [comment]
Just added 😉
<img width="1339" alt="Screenshot 2024-11-29 at 3 40 40 PM" src="https://github.com/user-attachments/assets/3a83cdca-11d6-4091-b7e4-28b9ff1987c6">

**Comment by AlexTheZoomer** [comment]
> Just added 😉
> <img width="1339" alt="Screenshot 2024-11-29 at 3 40 40 PM" src="https://github.com/user-attachments/assets/3a83cdca-11d6-4091-b7e4-28b9ff1987c6">
> 

Love it! How is the backend dealing with differing CRN's for different time slots?

**Comment by theobourgeois** [comment]
@AlexTheZoomer Didn't know CRNs work like that... Thanks for letting me know. I'll work on a better solution.

**Comment by theobourgeois** [comment]
@AlexTheZoomer Added CRN for different time slots in two different areas. It's shown as a badge next to the class name. It's also shown in a dialog upon clicking a time slot. Let me know what you think.

<img width="1344" alt="Screenshot 2024-11-29 at 4 15 59 PM" src="https://github.com/user-attachments/assets/97285ed8-012d-4437-9edc-c380ecbd7184">
<img width="1333" alt="Screenshot 2024-11-29 at 4 16 41 PM" src="https://github.com/user-attachments/assets/34dc31df-7f7a-4097-b086-1b47fc3775b6">
