### ISSUE TITLE
Ability to search by term?

### ISSUE THREAD

**Issue by xzeck** [theobourgeois/DalSearch#6]
Can we add the ability to search by term? Like a way to see what courses are offered in a particular term?

**Comment by theobourgeois** [comment]
You should be able to filter by term in the explore page 
<img width="1640" alt="Screenshot 2024-12-22 at 1 36 12 AM" src="https://github.com/user-attachments/assets/b8568a5a-236d-4735-8e2c-43b9a69b5427" />

**Comment by xzeck** [comment]
Got it, Closing the thread
